Merging cps++_QUDA_1 QUDA (DWF/Wilson) interface to CPS
git-svn-id: file:///home/chulwoo/CPS/repo/CVS2SVN/cps/trunk@4400 fb734a29-28db-4bc5-88a3-3cb5ee595545

diff --git a/cps_pp/configure.in b/cps_pp/configure.in
--- a/cps_pp/configure.in
+++ b/cps_pp/configure.in
@@ -2,13 +2,13 @@ dnl--------------------------------------------------------------------
 dnl  CVS keywords
 dnl
 dnl  $Author: chulwoo $
-dnl  $Date: 2012-08-10 21:25:12 $
-dnl  $Header: /home/chulwoo/CPS/repo/CVS/cps_only/cps_pp/configure.in,v 1.82 2012-08-10 21:25:12 chulwoo Exp $
-dnl  $Id: configure.in,v 1.82 2012-08-10 21:25:12 chulwoo Exp $
+dnl  $Date: 2012-12-05 16:39:19 $
+dnl  $Header: /home/chulwoo/CPS/repo/CVS/cps_only/cps_pp/configure.in,v 1.83 2012-12-05 16:39:19 chulwoo Exp $
+dnl  $Id: configure.in,v 1.83 2012-12-05 16:39:19 chulwoo Exp $
 dnl  $Name: not supported by cvs2svn $
 dnl  $Locker:  $
 dnl  $RCSfile: configure.in,v $
-dnl  $Revision: 1.82 $
+dnl  $Revision: 1.83 $
 dnl  $Source: /home/chulwoo/CPS/repo/CVS/cps_only/cps_pp/configure.in,v $
 dnl  $State: Exp $
 dnl
@@ -434,6 +434,56 @@ if test "$TESTING_PARALLEL" = "yes"; then
 else
    ENABLE_PARALLEL="undef PARALLEL"
 fi
+dnl -------------------------windy---------------------------
+dnl  Edited by hjkim. This configuration is need by QUDA&CUDA
+dnl -------------------------windy---------------------------
+dnl Are we compiling with QUDA GPU library?
+dnl Check whether --enable-cuda was given.
+AC_ARG_ENABLE(cuda, 
+	AC_HELP_STRING([--enable-cuda], 
+		[Location of CUDA installation. (default=no)]), 
+	,[enable_cuda="no"])
+AC_MSG_CHECKING([if including CUDA])
+AC_MSG_RESULT($enable_cuda)
+
+dnl Check whether --enable-quda was given.
+AC_ARG_ENABLE(quda, 
+	AC_HELP_STRING([--enable-quda], 
+		[Compile with QUDA GPU lib. (default=no)]), 
+	,[enable_quda="no"])
+AC_MSG_CHECKING([if including QUDA])
+AC_MSG_RESULT($enable_quda)
+
+dnl QUDA was given first and CUDA was given later, 
+dnl this is because library dependency.
+if test "$enable_quda" != "no"; then
+   if test "X${QUDA_DIR}X" = "XX"; then
+dnl     echo "QUDA_DIR environment variable not set"
+     QUDA_DIR=${enable_quda}
+   fi
+   INCLUDE_FLAGS="${INCLUDE_FLAGS} -I${QUDA_DIR}/include"
+   LDFLAGS="${LDFLAGS} -L${QUDA_DIR}/lib -lquda"
+   DFLAGS="${DFLAGS} -DUSE_QUDA"
+fi
+
+if test "$enable_cuda" != "no"; then
+   if test "X${CUDA_DIR}X" = "XX"; then
+dnl     echo "CUDA_DIR environment variable not set"
+     CUDA_DIR=${enable_cuda}
+   fi
+   INCLUDE_FLAGS="${INCLUDE_FLAGS} -I${CUDA_DIR}/include"
+   LDFLAGS="${LDFLAGS} -L${CUDA_DIR}/lib64 -lcudart"
+fi
+
+dnl If --enable-cuda was given for --enable-quda case, program will stop.
+if test "$enable_quda" != "no"; then
+   if test "X${CUDA_DIR}X" = "XX"; then
+     echo "CUDA_DIR environment variable not set (required for QUDA)"
+     exit 1
+   fi
+fi
+#-------------------------windy---------------------------	
+
 	
 dnl Shall we use the cps namespace?
 AC_ARG_ENABLE(namespace, 
