Merging with multibuild
git-svn-id: file:///home/chulwoo/CPS/repo/CVS2SVN/cps/trunk@243 fb734a29-28db-4bc5-88a3-3cb5ee595545

diff --git a/cps_pp/configure.in b/cps_pp/configure.in
--- a/cps_pp/configure.in
+++ b/cps_pp/configure.in
@@ -1,69 +1,175 @@
 dnl--------------------------------------------------------------------
 dnl  CVS keywords
 dnl
-dnl  $Author: zs $
-dnl  $Date: 2003-10-21 15:34:42 $
-dnl  $Header: /home/chulwoo/CPS/repo/CVS/cps_only/cps_pp/configure.in,v 1.3 2003-10-21 15:34:42 zs Exp $
-dnl  $Id: configure.in,v 1.3 2003-10-21 15:34:42 zs Exp $
+dnl  $Author: chulwoo $
+dnl  $Date: 2004-01-13 20:38:56 $
+dnl  $Header: /home/chulwoo/CPS/repo/CVS/cps_only/cps_pp/configure.in,v 1.4 2004-01-13 20:38:56 chulwoo Exp $
+dnl  $Id: configure.in,v 1.4 2004-01-13 20:38:56 chulwoo Exp $
 dnl  $Name: not supported by cvs2svn $
 dnl  $Locker:  $
 dnl  $RCSfile: configure.in,v $
-dnl  $Revision: 1.3 $
+dnl  $Revision: 1.4 $
 dnl  $Source: /home/chulwoo/CPS/repo/CVS/cps_only/cps_pp/configure.in,v $
 dnl  $State: Exp $
 dnl
 dnl--------------------------------------------------------------------
 AC_INIT(./src/)
 
-dnl Get host information:
+dnl Get host and target information:
+AC_CANONICAL_SYSTEM
 
-AC_CANONICAL_HOST
-AC_CANONICAL_TARGET
+dnl Set correct compiler information
+if test "$cross_compiling" = "yes"; then
+   AC_CHECK_PROGS(CXX, ${host_alias}-g++)
+   AC_CHECK_PROGS(LD, ${host_alias}-ld)
+   AC_CHECK_PROGS(AR, ${host_alias}-ar)
+   AC_CHECK_PROGS(AS, ${host_alias}-as)
+   if test -z "$CXX" || test -z "$LD" || test -z "$AR" || test -z "$AS"; then
+     echo "Missing required cross-compilation tools"
+     exit 1
+   fi
+else
+dnl check if Intel compiler is available if running on 686
+   if test "$host" = "i686-pc-linux-gnu" && \
+   test "$build" = "i686-pc-linux-gnu"; then
+       AC_CHECK_PROGS(CC, icc, gcc)
+       AC_CHECK_PROGS(CXX, icc, g++)
+   else
+     AC_CHECK_PROGS(CXX, g++)
+   fi
+   AC_CHECK_PROGS(LD, ld)
+   AC_CHECK_PROGS(AR, ar)
+   AC_CHECK_PROGS(AS, as)
+   if test -z "$CXX" || test -z "$LD" || test -z "$AR" || test -z "$AS"; then
+     echo "Missing required compilation tools"
+     exit 1
+   fi
+fi
 
 dnl If using this script, then we are not making the QCDSP version.
-
 NOT_TESTING_QCDSP="yes"
 AC_SUBST(NOT_TESTING_QCDSP)
-TARGET_QCDSP=0
-AC_SUBST(TARGET_QCDSP)	
+
+dnl installdir
+AC_ARG_ENABLE(installdir,
+[  --enable-installdir   What target are we compiling for? (default=noarch)] ,
+, [enable_installdir=`pwd`])
+AC_SUBST(enable_installdir)
+AC_MSG_CHECKING("Install directory")
+AC_MSG_RESULT($enable_installdir)
 
 dnl Check for maths library
-
 AC_CHECK_LIB(m, sin, ,echo "CPS needs the math library - bailing out"; exit 1)
 
-dnl Parallel (MPI) v. serial switch.
+dnl Set the relevant include files
+topwd_srcdir=`pwd` 
+AC_SUBST(topwd_srcdir)
+INCLUDE_FLAGS="-I\${BUILDDIR} -I\${SRCDIR}/include"
 
-AC_ARG_ENABLE(parallel-mpi, 
-[  --enable-parallel-mpi   Compile as a parallel code, using MPI. (default=no)] ,  , [enable_parallel_mpi="no"])
-AC_MSG_CHECKING([if parallel-mpi is enabled])
-AC_MSG_RESULT($enable_parallel_mpi)
-if test "$enable_parallel_mpi" = "yes"; then
-  PARALLEL=1	
-  AC_CHECK_PROGS(CXX, mpic++ mpiCC, g++)
-  if test "$CXX" = "g++"; then
-    AC_MSG_WARN([Using g++])
-    AC_SEARCH_LIBS(MPI_Init, mpi mpich, ,echo "CPS needs the MPI library for a parallel build - bailing out."; exit 1)
-  fi
-  MPILINK="-lmpi"
-  PARALLELLINK="MPILIB"
-  TESTING_PARALLEL="yes";
+dnl What target are we compiling for?
+AC_ARG_ENABLE(target, 
+[  --enable-target   What target are we compiling for? (default=noarch)] ,  , [enable_target="noarch"])
+AC_MSG_CHECKING("what target we are compiling for")
+AC_MSG_RESULT($enable_target)
+
+CFLAGS=""
+CXXFLAGS=""
+dnl Can add more cases as we need to, e.g. QCDSP
+if test "$enable_target" = "qcdoc"; then
+   CC="env GCC_EXEC_PREFIX=\${QOS}/quser/gcc-lib-user/// ${CC}"
+   CXX="env GCC_EXEC_PREFIX=\${QOS}/quser/gcc-lib-user/// ${CXX}"
+   AS="env GCC_EXEC_PREFIX=\${QOS}/quser/gcc-lib-user/// ${AS}"
+   AR="env GCC_EXEC_PREFIX=\${QOS}/quser/gcc-lib-user/// ${AR}"
+   LD="env GCC_EXEC_PREFIX=\${QOS}/quser/gcc-lib-user/// ${LD}"
+   INCLUDE_FLAGS="-I\${QOS}/quser/include -I\${QOS}/quser_qker/include -I\${QOS}/qhost_qker ${INCLUDE_FLAGS}"
+   CFLAGS="-Wa,-m405 -fno-exceptions -fno-hosted"
+   CXXFLAGS="-Wa,-m405 -fno-exceptions -fno-hosted"
+   ASFLAGS="-m405"
+   LDFLAGS="-Wa,\"-init _start\""
+
+   ARCH="QCDOC"
+   ARCHDIR="QCDOC_DIR"
+   DFLAGS="-DTARGET=1 -DPARALLEL=1"
+   TESTING_PARALLEL="yes";
+
+elif test "$enable_target" = "mpi"; then
+   AC_CHECK_PROGS(CXX, mpic++ mpiCC mpCC, g++)
+   if test "$CXX" = "g++"; then
+     AC_MSG_WARN([Using g++])
+     AC_SEARCH_LIBS(MPI_Init, mpi mpich, ,echo "CPS needs the MPI library for a parallel build - bailing out."; exit 1)
+   fi
+   DFLAGS="-DTARGET=3 -DPARALLEL=1"
+   LDFLAGS="-lmpi"
+   TESTING_PARALLEL="yes";
+   ARCH=MPI
+   ARCHDIR="MPI_DIR"
+
 else
-  PARALLEL=0
-  AC_PROG_CXX
-  MPILINK=""
-  PARALLELLINK="SERIALLIB"
-  TESTING_PARALLEL="no";
+
+   DFLAGS="-DTARGET=0 -DPARALLEL=0"
+   ARCH=NOARCH
+   ARCHDIR="NOARCH_DIR"
+   TESTING_PARALLEL="no";
 fi
-AC_SUBST(PARALLEL)
-AC_SUBST(MPILINK)
-AC_SUBST(PARALLELLINK)
+
+
+dnl Need to put in machine/compiler specific optimisation flags here
+AC_ARG_ENABLE(optimise, 
+[  --enable-optimise   Compile with maximum optimisation. (default=yes)] ,  , [enable_optimise="yes"])
+AC_MSG_CHECKING("if optimising")
+AC_MSG_RESULT($enable_optimise)
+if test "$enable_optimise" = "yes"; then
+   CFLAGS="${CFLAGS} -O3"
+   CXXFLAGS="${CXXFLAGS} -O3"
+fi
+
+
+dnl -O0 flag should overide any previous optimisation declarations
+AC_ARG_ENABLE(debug, 
+[  --enable-debug   Compile with debug information. (default=no)] ,  , [enable_debug="no"])
+AC_MSG_CHECKING("if debugging")
+AC_MSG_RESULT($enable_debug)
+if test "$enable_debug" = "yes"; then
+   CFLAGS="${CFLAGS} -g -O0"
+   CXXFLAGS="${CXXFLAGS} -g -O0"
+fi
+
+DFLAGS=""
+if test "$TESTING_PARALLEL" = "yes"; then
+   ENABLE_PARALLEL="define PARALLEL"
+else
+   ENABLE_PARALLEL="undef PARALLEL"
+fi
+	
+
+dnl Make visible all variables declared above
+AC_SUBST(AR)
+AC_SUBST(ARCH)
+AC_SUBST(ARCHDIR)
+AC_SUBST(AS)
+AC_SUBST(ASFLAGS)
+AC_SUBST(CFLAGS)
+AC_SUBST(CXXFLAGS)
+AC_SUBST(DFLAGS)
+AC_SUBST(INCLUDE_FLAGS)
+AC_SUBST(LD)
+AC_SUBST(LDFLAGS)
 AC_SUBST(TESTING_PARALLEL)
+AC_SUBST(ENABLE_PARALLEL)
+
+dnl temporary hack until qos is more mature
+if test "$enable_target" = "qcdoc"; then
+   CWD="/host/${USER}"
+else
+   CWD=""
+fi
+AC_SUBST(CWD)
+
 
 dnl Basic float/double precision switch:
-
 AC_ARG_ENABLE(double-prec, 
 [  --enable-double-prec    Force the code to use double precision throughout (default=yes)] ,  , [enable_double_precision="yes"])
-AC_MSG_CHECKING([if double-prec is enabled])
+AC_MSG_CHECKING("if double-prec is enabled")
 AC_MSG_RESULT($enable_double_precision)
 if test "$enable_double_precision" = "yes"; then
   GSUMPRECISION="double"
@@ -76,22 +182,19 @@ AC_SUBST(GSUMPRECISION)
 AC_SUBST(LOCALPRECISION)
 
 
-dnl Set default value for CXXFLAGS if none is defined or it's empty
-
-if test -z "$CXXFLAGS"; then
-  CXXFLAGS="-O"
-fi
-
-
-topwd_srcdir=`pwd` 
-AC_SUBST(topwd_srcdir)
-
 AC_PROG_INSTALL
 
 AC_CHECK_PROG(have_doxygen, doxygen, "yes")
 
+
 AC_OUTPUT(Makefile_cps\
-          tests/Makefile_common \
 	  config.h \
+	  Makefile \
+	  Makefile.vars \
+	  Makefile.rules \
+	  Makefile.compile \
+	  Makefile_depend \
+          tests/Makefile_common \
+          tests/Makefile_common2 \
           tests/regression.pl )
 
